# Generated by Django 5.1.1 on 2024-09-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_userprofile_options_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
