# Generated by Django 5.1.1 on 2024-09-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_userprofile_bio_userprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
